#!/bin/bash
#
# Reverse Proxy Configuration Helper for Synology
# This script helps verify and document reverse proxy settings
#

echo "=========================================="
echo "Reverse Proxy Configuration Helper"
echo "=========================================="
echo ""
echo "Domain: uploader.atozflooringsolutions.com.au"
echo "Container Port: 5007"
echo "Direct Access: http://192.168.0.201:5007"
echo ""
echo "=========================================="
echo "Synology Reverse Proxy Setup"
echo "=========================================="
echo ""
echo "1. Open Synology DSM: http://192.168.0.201:5000"
echo "2. Go to: Control Panel > Login Portal"
echo "3. Click: Advanced tab"
echo "4. Click: Reverse Proxy"
echo ""
echo "5. Create/Edit Rule with these settings:"
echo ""
echo "   General:"
echo "   - Name: uploader-atoz"
echo ""
echo "   Source (HTTP):"
echo "   - Hostname: uploader.atozflooringsolutions.com.au"
echo "   - Port: 80"
echo ""
echo "   Destination:"
echo "   - Hostname: localhost"
echo "   - Port: 5007"
echo ""
echo "6. Enable the rule (green toggle)"
echo "7. Click Apply"
echo ""
echo "=========================================="
echo "DNS Configuration Required"
echo "=========================================="
echo ""
echo "For the domain to work, configure DNS:"
echo ""
echo "Option 1: Hosts File (Local computers only)"
echo "  Windows: C:\\Windows\\System32\\drivers\\etc\\hosts"
echo "  Add: 192.168.0.201    uploader.atozflooringsolutions.com.au"
echo ""
echo "Option 2: Router DNS (Entire network)"
echo "  Add DNS entry: uploader.atozflooringsolutions.com.au -> 192.168.0.201"
echo ""
echo "Option 3: Public DNS (If domain is public)"
echo "  Add A record: uploader.atozflooringsolutions.com.au -> Your NAS public IP"
echo ""
echo "=========================================="
echo "Testing"
echo "=========================================="
echo ""
echo "Test direct access (should work now):"
echo "  curl http://192.168.0.201:5007"
echo ""
echo "Test domain access (after DNS configured):"
echo "  curl http://uploader.atozflooringsolutions.com.au"
echo ""




